require: rubocop-rspec

inherit_from:
  - https://raw.githubusercontent.com/psu-stewardship/guides/master/style/ruby/.rubocop.yml
  - .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4.1
  Excludes:
    - node_modules/**/*
    - db/**/*
    - tmp/**/*
    - bin/**/*

RSpec/DescribeClass:
  Exclude:
    - 'spec/**/*'

RSpec/ExampleLength:
  Exclude:
    - 'spec/**/*'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/**/*'
